version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
    depends_on:
      - db
    volumes:
      - ./:/app/
      - /app/node_modules

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
    - POSTGRES_PORT=${DB_PORT}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_HOST=${DB_HOST}
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data 
      

networks:
  db:
    driver: bridge

